baseurl = "https://cleanunicorn.xyz"
title = "Daniel Luca"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
relativeURLs = true
canonifyurls = true

paginate = 5

pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsUseClasses = true

# Blackfriday renderer
[blackfriday]
    hrefTargetBlank = true
	# plainIDAnchors = true

disqusShortname = "disqussname"

[params]
    author = "Daniel Luca"
    info = "Developer and security researcher"
    description = "Daniel Luca's personal website"
    keywords = "blog,developer,personal,security,ethereum,blockchain"
    avatarurl = "images/me.png"

    favicon_32 = "images/favicon-32x32.png"
    favicon_16 = "images/favicon-16x16.png"

    footercontent = "\"We are the music makers and we are the dreamers of dreams\" Ode by Arthur O'Shaughnessy"

    hidecredits = true
    hidecopyright = true

    rtl = false

    math = false
    custom_css = [
        "css/syntax.css", 
        "css/custom.css"
    ]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 4
    url = "https://github.com/cleanunicorn/"
[[params.social]]
    name = "Gitlab"
    icon = "fab fa-gitlab fa-2x"
    weight = 3
    url = "https://gitlab.com/cleanunicorn/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 2
    url = "https://twitter.com/cleanunicorn/"
[[params.social]]
    name = "Stackoverflow"
    icon = "fab fa-stack-exchange fa-2x"
    weight = 1
    url = "https://ethereum.stackexchange.com/users/6253/cleanunicorn"    
[[params.social]]
    name = "Medium"
    icon = "fab fa-medium fa-2x"
    weight = 1
    url = "https://medium.com/@cleanunicorn"        

# Menu links
[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
[[menu.main]]
    name = "Blog"
    weight = 2
    url = "/blog/"

